const getBookData = () => ([
    {
        id: 1,
        image: '/images/book-moment.png',
        title: 'A Moment To Decide',
        location: 'Sumatera Selatan',
        author: 'Dian Dhie',
        owner: '@mikhaya',
        durationInMonths: "2 bulan",
        available: true,
        category: 'Romance',
        peminjam: 10,
    },
    {
        id: 2,
        image: '/images/book-priyayi.png',
        title: 'Para Priyayi',
        location: 'Lampung',
        author: 'Umar K',
        owner: '@amarullah01',
        durationInMonths: "2 bulan",
        available: true,
        category: 'Romance',
        peminjam: 10,
    },
    {
        id: 3,
        image: '/images/book-alchemist.png',
        title: 'The Alchemist',
        location: 'Jawa Timur',
        author: 'Paulo C',
        owner: '@amarullah01',
        durationInMonths: "2 bulan",
        available: true,
        category: 'Adventure',
        peminjam: 10,
    }, 
    {
        id: 4,
        image: '/images/book-tentangkita.png',
        title: 'Tentang Kita',
        location: 'Banten',
        author: 'Tere Liye',
        owner: '@faishaumi',
        durationInMonths: "2 bulan",
        available: true,
        category: 'Romance',
        peminjam: 10,
    }, 
    // {
    //     id: 5,
    //     image: '/images/book-storyofkiran.png',
    //     title: 'Story of Kiran',
    //     location: 'Jawa Barat',
    //     author: 'Imam Nur',
    //     owner: 'marzy',
    //     durationInMonths: "2 bulan",
    //     available: true,
    //     category: 'Romance'
    // }, 
])

export {getBookData};