const getBookData = () => ([
    {
        id: 1,
        image: '/images/book-moment.png',
        image2: '/images/book-priyayi.png',
        image3: '/images/book-alchemist.png',
        title: 'A Moment To Decide',
        location: 'Sumatera Selatan',
        author: 'Dian Dhie',
        owner: '@mikhaya',
        avatar: '/images/user-mikhaya.png',
        durationInMonths: "2 bulan",
        available: true,
        category: 'Romance',
        peminjam: 10,
        description: 'Buku yang menurut saya sangat asik untuk dibaca, untuk kalian yang ingin membaca komik yang seru, saya rekomendasikan untuk baca ini. Saya berharap buku ini akan terus dilanjutkan. Biar makin banyak bibit-bibit orang hebat di negeri kita!'
    },
    {
        id: 2,
        image: '/images/book-priyayi.png',
        image2: '/images/book-priyayi.png',
        image3: '/images/book-alchemist.png',
        title: 'Para Priyayi',
        location: 'Lampung',
        author: 'Umar K',
        owner: '@amarullah01',
        avatar: '/images/user-mikhaya.png',
        durationInMonths: "2 bulan",
        available: true,
        category: 'Romance',
        peminjam: 10,
        description: 'Buku yang menurut saya sangat asik untuk dibaca, untuk kalian yang ingin membaca komik yang seru, saya rekomendasikan untuk baca ini. Saya berharap buku ini akan terus dilanjutkan. Biar makin banyak bibit-bibit orang hebat di negeri kita!'
    },
    {
        id: 3,
        image: '/images/book-alchemist.png',
        image2: '/images/book-priyayi.png',
        image3: '/images/book-alchemist.png',
        title: 'The Alchemist',
        location: 'Jawa Timur',
        author: 'Paulo C',
        owner: '@amarullah01',
        avatar: '/images/user-mikhaya.png',
        durationInMonths: "2 bulan",
        available: true,
        category: 'Adventure',
        peminjam: 10,
        description: 'Buku yang menurut saya sangat asik untuk dibaca, untuk kalian yang ingin membaca komik yang seru, saya rekomendasikan untuk baca ini. Saya berharap buku ini akan terus dilanjutkan. Biar makin banyak bibit-bibit orang hebat di negeri kita!'
    }, 
    {
        id: 4,
        image: '/images/book-tentangkita.png',
        image2: '/images/book-priyayi.png',
        image3: '/images/book-alchemist.png',
        title: 'Tentang Kita',
        location: 'Banten',
        author: 'Tere Liye',
        owner: '@faishaumi',
        avatar: '/images/user-mikhaya.png',
        durationInMonths: "2 bulan",
        available: true,
        category: 'Romance',
        peminjam: 10,
        description: 'Buku yang menurut saya sangat asik untuk dibaca, untuk kalian yang ingin membaca komik yang seru, saya rekomendasikan untuk baca ini. Saya berharap buku ini akan terus dilanjutkan. Biar makin banyak bibit-bibit orang hebat di negeri kita!'
    }, 
    // {
    //     id: 5,
    //     image: '/images/book-storyofkiran.png',
    //     title: 'Story of Kiran',
    //     location: 'Jawa Barat',
    //     author: 'Imam Nur',
    //     owner: 'marzy',
    //     durationInMonths: "2 bulan",
    //     available: true,
    //     category: 'Romance'
    // }, 
])

export {getBookData};